# Specifies your Active Directory ID:
azure.activedirectory.tenant-id=e12c9f8e-ecb3-4cbd-b504-9410ab9116ae

# Specifies your App Registration's Application ID:
spring.security.oauth2.client.registration.azure.client-id=e796f1b3-3b4f-47cd-9122-b4b573ed67e7

# Specifies your App Registration's secret key:
spring.security.oauth2.client.registration.azure.client-secret=McC0Y6T~qV~krH9Dz.we9vS5nQ3f~_Ej2O

# Specifies the list of Active Directory groups to use for authorization:
azure.activedirectory.active-directory-groups=users

server.port=8091
#debug=true

server.servlet.context-path=/

#server.contextPath=/springbootapp
#server.servlet.contextPath=/

server.forward-headers-strategy=NATIVE
redirect_uri=https://koolkdemo.azurewebsites.net/login/oauth2/code/azure